### ISSUE TITLE
azurerm / azuread no longer update after moving to hashicorp org / plugin-sdk migration

### ISSUE THREAD

**Issue by timja** [VladRassokhin/terraform-metadata#14]
Hello

I've been maintaining my own fork but I've gotten stuck trying to update the azurerm schema since it moved to the hashicorp org.

I've defined it as:
```
  "azurerm": {
    "repository": "github.com/hashicorp/terraform-provider-__NAME__",
    "pkg_name": "internal/services"
  },
```

and I get:

```
package command-line-arguments
	imports github.com/hashicorp/terraform-provider-azurerm/internal/services: no Go files in /Users/timja/projects/go/src/github.com/hashicorp/terraform-provider-azurerm/internal/services
Finished azurerm
```

Has anyone been able to make this work?
In general updating this metadata is in a sorry state right now.

@VladRassokhin are you still around and looking at this / know if there's someone maintaining this?

**Comment by M1kep** [comment]
I was messing with this a few months back, and it is indeed quite the journey. For this specific issue, updating pkg_name to be `internal/provider` should fix the issue. 

This can be located from within the providers source generally. In this case, in main.go of the provider you can see that the provider being used is defined in `internal/provider/provider.go` and imported as `github.com/hashicorp/terraform-provider-azurerm/internal/provider`

https://github.com/hashicorp/terraform-provider-azurerm/blob/main/main.go

**Comment by timja** [comment]
Any chance you have a branch?

I'm now hitting:

```
Generating schema for azurerm
# command-line-arguments
generate-schema/generate-schema.go:298:13: undefined: provider.Provider
```

will try have a closer look later

**Comment by timja** [comment]
Hmm I'll take a look at https://github.com/VladRassokhin/terraform-metadata/compare/master...cageyv:sync-meta-202105?expand=1 next

**Comment by timja** [comment]
Above still fails on https://github.com/VladRassokhin/terraform-metadata/blob/master/schemas-extractor/template/provider/terraform-plugin-sdk-v2/generate-schema.go#L298 with azurerm provider

**Comment by cageyv** [comment]
@timja this probably solved 
Can you try a fork?

**Comment by timja** [comment]
I've updated to the fork and the resource that was missing / outdated now works!

Huge thanks to all who contributed to this.

**Comment by timja** [comment]
Also looks like @VladRassokhin has done some fixes too:
https://github.com/VladRassokhin/terraform-metadata/commits/master
